import type { Metadata } from "next";
import RootLayout from "./RootLayout";
import Footer from "../components/ui/Footer";

// Metadata is exported from the server component
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Use RootLayout as the child in this server component
export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <RootLayout>
      {children}
      <Footer />  
    </RootLayout>
  )
}
